import Navbar from "@/components/Navbar";
import { chainData, wagmiConfigData } from "@/services/wagmi";
import { RainbowKitProvider } from "@rainbow-me/rainbowkit";
import "@rainbow-me/rainbowkit/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { WagmiConfig } from "wagmi";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WagmiConfig config={wagmiConfigData}>
          <RainbowKitProvider chains={chainData} modalSize="wide">
            <Navbar />
            <main>{children}</main>
          </RainbowKitProvider>
        </WagmiConfig>
      </body>
    </html>
  );
}
